### PR TITLE
Feature/calendar widget

### PR DESCRIPTION
**Pull request by mpu-creare**
Making PR to track calendar widget creation.

### CODE REVIEW

**Review by dsully-dev — COMMENTED** [review]
Note this is still for #11

**Review by dsully-dev — COMMENTED** [review]
@mpu-creare Can you review this? I believe this should work, but am not getting back images for each tile. Rather, I'm getting .exe files. From what I can tell, I'm updating the url correctly, but replacing `/usdm_.*_wms/` with `"usdm_" + moment.format('YYYYMMDD') + "_wms"`. 

I'm also curious if you'd prefer I do this some other way, more similar to how the plot view queries NDMI data for the last 30 days.

**Comment by mpu-creare** [comment]
Looks like the *LAYER NAME* in the query string does not have an underscore. Mind fixing it?

This WORKS:
http://ndmc-001.unl.edu:8080/cgi-bin/mapserv.exe?map=/ms4w/apps/usdm/service/usdm_20200310_wms.map&&service=WMS&request=GetMap&layers=usdm20200310&styles=&format=image%2Fpng&transparent=true&version=1.1.1&transparency=true&width=256&height=256&srs=EPSG%3A3857&bbox=-13462700.917811524,5009377.085697314,-13306157.883883484,5165920.119625352 

This DOES NOT work (current implementation):
http://ndmc-001.unl.edu:8080/cgi-bin/mapserv.exe?map=/ms4w/apps/usdm/service/usdm_20200310_wms.map&&service=WMS&request=GetMap&layers=usdm_20200310&styles=&format=image%2Fpng&transparent=true&version=1.1.1&transparency=true&width=256&height=256&srs=EPSG%3A3857&bbox=-13462700.917811524,5009377.085697314,-13306157.883883484,5165920.119625352

**Comment by dsully-dev** [comment]
Good catch, thank you! I fixed it and it looks to be working well! I should note, as of now, I restrict the date picker's `minDate` to the first day NDMI data appears on their [site](https://droughtmonitor.unl.edu/Data/GISData.aspx), and those available dates weekly since that date are hard coded. Note that this will restrict users from getting SMAP data prior to `2000-01-04`. We could add some logic to only use that `minDate` when the NDMI layer is on.

**Comment by dsully-dev** [comment]
All set once you review, @mpu-creare

**Comment by mpu-creare** [comment]
The NDMI works really well. Nice work. I'll have to dig into why the Drought monitor is not working, hopefully a little later this week. 

This will need some style updates, but I'll make another PR for that.

**Pull request merged**
